### ISSUE TITLE
get currently uploading file

### ISSUE THREAD

**Issue by astroanu** [morris/vinyl-ftp#1]
Love it.. working like a charm. is there a way to get currently uploading file?

**Comment by morris** [comment]
I'm glad you like it! You could patch the upload method of the connection:

	var conn = ftp.create( { /* ... */ } );
	var upload = conn.upload;
	conn.upload = function( file, path, cb ) {
		if ( !file.isNull() ) console.log( file, path ); // use file and path for something
		upload.call( this, file, path, cb );
	};

What exactly are you trying to achieve? Maybe it's something I should add to the package, or maybe there's a better way.

**Comment by astroanu** [comment]
sorry for the lack of details. When i run the gulp task it doesn't show anything on the terminal. So i want to print the current file name on to the terminal window.

    var conn = ftp.create({
         host:     'xxx',
         user:     'xxx',
         password: 'xxx',
         parallel: 10
    });
    var globs = [
         'app/**',
         'bootstrap/**',
        ];

        return gulp.start('default')

        .src(globs, {base: '.', buffer: false})

        .pipe(conn.newer('/'))
        .pipe(conn.dest('/', function(){
                // i want to print the file being upload
               // process.stdout.write(filename+ '\n');
         }))

**Comment by morris** [comment]
For that you can just set a logging function like gutil.log/console.log on the connection. The built-in logging which will give you upload progress and more:

    var gutil = require( 'gulp-util' );
    var conn = ftp.create({
        /* connection details... */
        log: gutil.log
    });

**Comment by astroanu** [comment]
wow i didn't know about that. i'm new to gulp. thanks :)

**Comment by morris** [comment]
You're welcome :) just added a log setting to the readme example, too

**Comment by astroanu** [comment]
That's good !

**Comment by tnguyen14** [comment]
@morris I am using that `log: gutil.log`, but all I get on my terminal is this:

```
[15:40:48] Starting 'ftp'...
[15:40:48] CONN
[15:40:48] CONN
```

**Comment by morris** [comment]
@tnguyen14 please create a new issue with your gulpfile :)
