### ISSUE TITLE
how to exclude root local folder?

### ISSUE THREAD

**Issue by smlombardi** [morris/vinyl-ftp#11]
I have my local files for deployment in `./dist`

Currently, I am using this gulp script:
````
gulp.task('deploy', ['prompt_password'], function() {
  var conn = ftp.create({
    host: 'myhost',
    user: 'userName',
    password: userPass,
    parallel: 10,
    log: gutil.log
  });
  var globs = [
    'dist/**'
  ];

  return gulp.src(globs, {
      base: '.',
      buffer: false
    })

    .pipe(conn.dest('/sandbox/myApp'));

});
````

This correctly uploads everything in `dist` as it should to my `/sandbox/myApp` directory -- **EXCEPT** it also creates the dist folder in there, so now my URL is  `myserver.com/sandbox/myApp/dist/index.html`

Not horrible, but can it be avoided?

**Comment by morris** [comment]
Just change your base to 'dist' in gulp.src: `gulp.src(globs, { base: 'dist', buffer: false })...` - that should do the trick

**Comment by smlombardi** [comment]
of course.  Thanks.
