### ISSUE TITLE
Base is not being applied to globs on upload

### ISSUE THREAD

**Issue by folosophy** [morris/vinyl-ftp#110]
When I try to deploy a dist folder to assets using **base** the contents get uploaded to dist/assets instead of just assets, as if base is being completely ignored:

**Expected:** assets/js/...
**Result:** dist/assets/js/...

var globs = [
  'dist/assets/js**/*.js'
];

return gulp.src(globs,{
  cwd: 'wp-content/themes/example,
  base: 'dist',
  buffer: false
})
.pipe(conn.newer('.'))
.pipe(conn.dest('.'));

**Comment by kalinichenko88** [comment]
@folosophy yours code has error in globals var. Paths does not should begin with **dist** if you seting base param.
But, I have this problem too :-) My solves is removing `base` and set `cwd`:

```javascript
const globs = [
		'**',
		'index.html'
	];`

return gulp.src(globs, {cwd: 'build', buffer: false})
		.pipe(conn.dest('public'));
```
