### ISSUE TITLE
ERROR Error: Too many connections (8) from this IP

### ISSUE THREAD

**Issue by cagcak** [morris/vinyl-ftp#120]
Keep getting the error for the below configuration:

```
const connection = vinlyFTP.create({
        host:     'sample-host',
        user:     'sample-user',
        password: 'sample-pass',
        parallel: 10,
        maxConnections: 20,
        log:      gutil.log
    })
```

**Comment by simboonlong** [comment]
Think the number of maximum connections varies on hosting provider.

For mine, 5 works

```
parallel: 5,
maxConnections: 5,
```
Try lowering the numbers for both?

**Comment by cagcak** [comment]
Yes @simboonlong its obviously provider options don't let exceed specific accepted serial connection number. Your doubled option worked for me as well. Thanks.
