### ISSUE TITLE
Error: Create directory operation failed

### ISSUE THREAD

**Issue by littledu** [morris/vinyl-ftp#14]
**my code:**
```
return gulp.src('./dist/**/*', {base: '.', buffer: true}).pipe(conn.dest(dir))
```

the error message: Error: Create directory operation failed.

help me, please!

**Comment by morris** [comment]
please paste the complete gulp file and console output, as well as a list of local files. by the way `dist/**` should be enough

**Comment by littledu** [comment]
the console output:
![image](https://cloud.githubusercontent.com/assets/1784673/7365622/9b4820fe-edc4-11e4-984d-cf7e3120e75c.png)

the dist list:
![image](https://cloud.githubusercontent.com/assets/1784673/7365641/be8ded96-edc4-11e4-815f-7a20e3b3a4c1.png)

**Comment by littledu** [comment]
@morris 
hei , just delete the `return` ,and that is ok, so strange......

the new code: 
```
gulp.src('./dist/**/*', {base: '.', buffer: true}).pipe(conn.dest(dir))
```
