### ISSUE TITLE
Ignoring Files

### ISSUE THREAD

**Issue by nilssolanki** [morris/vinyl-ftp#16]
Is there a way to specify files to be ignored by the upload (like a ".ftpignore" file, or something similar)?

**Comment by morris** [comment]
Use the gulp.src glob patterns for that:

```javascript
gulp.src( [
    'src/**',
    'css/**',
    '!ignorethis' // negated pattern
] ).pipe( /* vinyl ftp... */ );
```

Check https://www.npmjs.com/package/glob-stream for examples
