### ISSUE TITLE
Set Permissions on Folder

### ISSUE THREAD

**Issue by DmitryEfimenko** [morris/vinyl-ftp#17]
I know that `conn.mode()` command sets permissions on files.
How can I set permissions on the folder?

**Comment by morris** [comment]
Actually it should work with directories, as long as the incoming stream also passes directories. You could also use conn.chmod( path, mode, callback ) which only sets the mode on a single path and does not return a stream.

**Comment by DmitryEfimenko** [comment]
`conn.chmod( path, mode, callback )` worked. Thanks
