### ISSUE TITLE
conn.chmod( path, mode, callback) does not exactly work

### ISSUE THREAD

**Issue by DmitryEfimenko** [morris/vinyl-ftp#18]
I have the following code running in gulp:
```
conn.chmod('myFile', '4755', function(){ console.log('changed'); });
```
it almost works. If I go the the terminal and run the following command `ll myFile` I'd get `-rwxr-xr-x`. However, if I directly run on the terminal `chmod 4755 myFile`, I'll get `-rwsr-xr-x`, which is what expected.

Any help is appreciated

**Comment by morris** [comment]
Are we talking about FTP? The chmod method sends a SITE CHMOD with mode and filename to the FTP server, that's how you set permission via FTP. It won't set any permissions on local files, though. Node's fs package has functions for that, i think.

**Comment by DmitryEfimenko** [comment]
yes, FTP. It's not on local machine. In fact, locally I'm running Windows, so I don't need to set any permissions locally.
The overview is that I have a gulp task that deploys local files via ftp to the Linux box. Once it deployed, it sets permissions there.

**Comment by Jabotical** [comment]
It looks like "SITE CHMOD" only sets 3-digit chmod codes, so no SUID/SGID/Sticky bits.

This is referenced here: http://www.xav.com/scripts/help/setuid.html
and here: http://php.net/manual/en/function.chmod.php

There is a probably a more definitive source somewhere else, but it wasn't immediately obvious.

**Comment by morris** [comment]
Thanks for the research @Jabotical - @DmitryEfimenko could you paste your vinyl-ftp log? It seems the "SITE CHMOD 4755 myFile" is sent to the server, but the server does not handle it correctly. So nothing vinyl-ftp could do about :-(

**Comment by DmitryEfimenko** [comment]
The log really had nothing useful in there and it looks like indeed vinyl-ftp won't be able to help me here, which is fine. Thanks for your time, everyone
