### ISSUE TITLE
Clean destination directory

### ISSUE THREAD

**Issue by XavierDupessey** [morris/vinyl-ftp#2]
Hi, is there a way to clean (empty) the FTP destination directory before the transfer begins?
It could be useful, I think...

**Comment by morris** [comment]
currently, no :( I just tried to add a quick solution, but this seems to be more involved because you have to delete the deepest files first. will look into it and publish a new version soon

**Comment by james-ingold** [comment]
+1 this feature would help me.

**Comment by morris** [comment]
Put way too much thought into this, as [mscdex/node-ftp](https://github.com/mscdex/node-ftp) already supports recursive rmdir. Just added `delete` and `rmdir` to v0.4.0 :)
