### ISSUE TITLE
Upload to different folder structure that locally

### ISSUE THREAD

**Issue by boedlen** [morris/vinyl-ftp#20]
I have a folders locally for all my assets called `/assets/_dist`, on my remote server i have an assets folder called `/assets`.

How can i upload the content of `/assets/_dist` to my remote `/assets` folder? 

I've tried a few things, but i always get paths like `/assets/_dist/js/frontend.min.js` or `/assets/assets/_dist/js/frontend.min.js` when what i want is `/assets/js/frontend.min.js`.

Currently i have this, but it's not working at all, and i cannot figure out what i need to change.

```javascript
var ftpConn = ftp.create( {
        host: sftpConfigContent.host,
        user: sftpConfigContent.user,
        password: sftpConfigContent.password,
        parallel: 10,
        log: gutil.log
});
var globs = [
    'assets/_dist/js/**',
    'assets/_dist/css/**'
];

gulp.task( 'ftp-css', function () {
     return gulp.src( globs, { base: '/files/templates/designs/mydesign/assets', buffer: false } )
         .pipe( ftpConn.newer( '/assets/_dist' ) ) // only upload newer files
         .pipe( ftpConn.dest( '/files/templates/designs/mydesign/assets' ) );
 } );
```

Any tips on what i should change are welcome.

**Comment by morris** [comment]
base should be ´assets/_dist´ and the ´newer´ should get the same (remote) path as `dest`. That should work.

**Comment by boedlen** [comment]
It works, but it does a little more than i expect.

I have these gulp task now.

```javascript
var ftpConn = ftp.create( {
        host: sftpConfigContent.host,
        user: sftpConfigContent.user,
        password: sftpConfigContent.password,
        parallel: 10,
        log: gutil.log
});
var globs = [
    'assets/_dist/js/**',
    'assets/_dist/css/**'
];

gulp.task( 'ftp-css', function () {
    return gulp.src( globs, { base: 'assets/_dist/css', buffer: false } )
        .pipe( ftpConn.newer( '/files/templates/designs/mydesign/assets/css' ) )
        .pipe( ftpConn.dest( '/files/templates/designs/mydesign/assets/css' ) );
} );

gulp.task( 'ftp-js', function () {
    return gulp.src( globs, { base: 'assets/_dist/js', buffer: false } )
        .pipe( ftpConn.newer( '/files/templates/designs/mydesign/assets/js' ) ) 
        .pipe( ftpConn.dest( '/files/templates/designs/mydesign/assets/js' ) );
} );
```

But when i call `gulp ftp-css` both my JS and CSS files are uploaded, i'd expect to only see my CSS files get uploaded.

Do i need a glob for JS and one for CSS to get this setup working, or should i do something else entirely?

**Comment by morris** [comment]
yes, you'd need separate globs. but i wouldn't use separate tasks in the first place

**Comment by boedlen** [comment]
I can see why one task would be enough, but i like the seperation of CSS and JS.
Having two globs work as intended.

Thank you for looking into my issue :smiley:
