### ISSUE TITLE
Unable to upload on a several seconds interval

### ISSUE THREAD

**Issue by t-prod** [morris/vinyl-ftp#23]
Hello,

First, thanks for your script. I have a problem when I try to upload with a 30 second interval.
We work sometime directly on the server so we need the compiled CSS on the FTP. We work with libsass too.

Here is my script. On stackoverflow they talk about the base parameter. http://stackoverflow.com/questions/29340264/vinyl-ftp-does-no-upload
```
var site_path = './sites/site1/t/assets/';
var admin_path = './admin/t/assets/';

 var globs = [
        site_path +'css/**',
        admin_path +'css/**'
    ];
 
    return gulp.src( globs, { base: '.', buffer: false } )
        .pipe( conn.dest( '/' ));
```

In my watch task when it works I have

CONN
READY
LIST
PUT
DISC
UP

When it doesn't works PUT and UP are not here.

What do you think ?

**Comment by morris** [comment]
This should definitely work. Are you saying this works sometimes and sometimes not? When does that 30 second interval happen? I also need the complete gulpfile if possible.

**Comment by t-prod** [comment]
Hi,

That's correct, it works only if the task is executed several minutes later OR if I save my scss file 2 times or 3 times.
Here is the gulpfile.js below
```
var gulp = require('gulp');
var sass = require('gulp-sass');
var minifycss = require('gulp-minify-css');
var gutil = require( 'gulp-util' );
var ftp = require( 'vinyl-ftp' );
var bower = require('gulp-bower');
var composer = require('gulp-composer');


var site_path = './sites/site1/t/assets/';
var admin_path = './admin/t/assets/';

gulp.task('sass', function () {
    // Website
    gulp.src(site_path + 'scss/*.scss')
    .pipe(sass())
    .pipe(minifycss())
    .pipe(gulp.dest(site_path + 'css'))
    
    //
    gulp.src(admin_path + 'scss/*.scss')
    .pipe(sass())
    .pipe(minifycss())
    .pipe(gulp.dest(admin_path + 'css'))
    //.pipe(reload({stream:true}))
});

gulp.task('watch', function() {
    gulp.watch(site_path + 'scss/*.scss', ['sass', 'deploy']);
});

gulp.task('install', function() {
  bower().pipe(gulp.dest('vendor/'))
  composer({ cwd: './', bin: 'composer' })
});

gulp.task( 'deploy', function() {
 
    var conn = ftp.create( {
        host:     'host',
        user:     'user',
        password: 'pwd',
        parallel: 10,
        maxConnections: 10,
        reload : true,
        log: gutil.log
    } );
 
    var globs = [
        site_path +'css/**',
        admin_path +'css/**'
    ];
 
    return gulp.src( globs, { base: '.', buffer: false } )
        .pipe( conn.dest( '/' ));
} );

// Default task to be run with `gulp`
gulp.task('default', ['sass', 'watch', 'deploy'], function () {
});
```
![image](https://cloud.githubusercontent.com/assets/1824638/8692553/8d6a6558-2acf-11e5-8693-bf46f50fdc9d.png)

Regards

**Comment by t-prod** [comment]
If I delete the app.css online, the PUT is always done. Maybe a date comparaison with the server ?

**Comment by t-prod** [comment]
Ok it works now, I was in 0.4.1 version, I've updated your package and that's ok (0.4.4).

Thanks

**Comment by morris** [comment]
Great :)
