### ISSUE TITLE
Improve README.md to warn about pushing gulpfile.js to public repo

### ISSUE THREAD

**Issue by hansspiess** [morris/vinyl-ftp#28]
thanks for this great tool! i started using it with pleasure, however, realized that a security pitfall could be for noobs like me to expose ftp credentials when pushing their project gulpfile.js to a public repo. you could point that out in README.md – but nevermind ;-)

**Comment by morris** [comment]
Ok, will add a note to the readme, thanks!

**Comment by Twansparant** [comment]
Better would be to place the FTP credentials in a separate config file so you can push the Gulpfile.js public repos. That's what Grunt ftpush does for example: https://github.com/inossidabile/grunt-ftpush

**Comment by morris** [comment]
You can always do this:

```
var ftp = require( 'vinyl-ftp' );
var config = require( 'config.json' );
gulp.task( 'deploy', function () {

    var conn = ftp.create( config );
} );
```

**Comment by Twansparant** [comment]
Yes thanks, that worked!
