### ISSUE TITLE
Error: Can't create socket at makeError …

### ISSUE THREAD

**Issue by stentebjerg** [morris/vinyl-ftp#29]
Hi guys,
I suddenly get this error. What to to?
![screen shot 2015-08-17 at 16 55 33](https://cloud.githubusercontent.com/assets/351323/9307809/e7621470-4500-11e5-935d-cf58b925e6d6.png)

**Comment by morris** [comment]
Have you updated to the latest version? I don't think this is vinyl-ftp related. It might be a network/firewall issue. Did something change in your network? Does a regular client like FileZilla work?

**Comment by stentebjerg** [comment]
I use sftp and Sublime with no problems. Maybe it is after the last Mac OSX update.

**Comment by stentebjerg** [comment]
And yes I running the latest version of vinyl-ftp

**Comment by morris** [comment]
Try running with `debug: console.log.bind( console )` and paste the generated log

**Comment by stentebjerg** [comment]
Hi Morris,
I deleted the folder and pulled it again. And now it is working. Very strange

**Comment by morris** [comment]
Yeah that's odd, anyway glad it works again :-)
