### ISSUE TITLE
Error: Considering directory a file + sometimes cannot find local dirs

### ISSUE THREAD

**Issue by smajl** [morris/vinyl-ftp#3]
Task:
```javascript
gulp.task('deploy', function () {
  var connection = ftp.create({
    host: '***',
    user: '***',
    pass: '***',
    log: $.util.log
  });

  return gulp.src(PATHS.build.dist.basePath + '**/*', { buffer: false })
    //.pipe(connection.newer('/'))
    .pipe(connection.dest('/'));
});
```
First deploy runs sometimes OK, sometimes **errors with**:
```
[17:34:07] Error: /jspm_packages/github/smajl/bootstrap@master/dist: No such file or directory
```
But the directory is always there. Anyway **after completing deploy I get this on every next try**:
```
[17:29:24] Starting 'deploy'...
[17:29:24] CONN 
[17:29:24] CONN 
[17:29:24] CONN 
[17:29:24] READY
[17:29:24] PUT   /index.html
[17:29:24] READY
[17:29:24] PUT   /jspm.conf.js
[17:29:24] READY
[17:29:24] MLSD  /
[17:29:24] UP    100% /index.html
[17:29:24] UP    100% /jspm.conf.js
[17:29:24] LIST  /
[17:29:24] ERROR [Error: /images is a file, cannot MKDIR]
[17:29:24] DISC 
[17:29:24] 'deploy' errored after 203 ms
```
Any idea? I deploy with gulp-ftp with same setup with no problem. :(

**Comment by morris** [comment]
As it's not really reproducable, the first issue seems to be somehow tied to other gulp tasks, maybe you can share your complete gulpfile?

About the second issue, I'm guessing the server sends a different MLSD response than my test servers, probably uppercase "DIR" for the file type. I just published a patch (v0.3.1) with an improved type check, hope this fixes that one. Let me know :)

**Comment by smajl** [comment]
Just had an opportunity to finally test your new release (0.3.3) and both issues seem to be now resolved, great! Thank you very much for the quick fix. :)

**Comment by morris** [comment]
great :) thanks for reporting!

**Comment by Fabryz** [comment]
Hello, I have seen that in some systems when you check whether the current file is a directory it returns "cdir". Could you please give it a look?

https://github.com/morris/vinyl-ftp/blob/master/lib/helpers.js#L45

I had to temporary fix it adding an "or" on the same condition === "c"

**Comment by morris** [comment]
great catch, thanks
