### ISSUE TITLE
Delete folder

### ISSUE THREAD

**Issue by cablegunmaster** [morris/vinyl-ftp#34]
I am trying to empty out a folder with this library and recreating it after.
  
conn.rmdir(remotePath + '/**');
Is this the line needed to remove all content in the folder, or does it only delete the folder itself, please , this requires more documentation.

**Comment by morris** [comment]
The readme says: conn.rmdir( path, cb ) - Removes a directory, recursively.
Globs are not supported in the path, however the folder and its contents are removed by just using conn.rmdir(remotePath, cb). Don't forget the callback.

**Comment by cablegunmaster** [comment]
Question is can i make multiple of these in a pipe ? Or 1 big callback ?

**Comment by morris** [comment]
Currently, one path per callback. I agree that it might be beneficial to have a streaming method with glob support.
