### ISSUE TITLE
MLSD - '500 Command not understood.

### ISSUE THREAD

**Issue by bartvanderwal** [morris/vinyl-ftp#35]
I'm getting an error `'500 Command not understood.`

I'll paste the full error message below. This issue seems very similar to #4. Which was closed per v0.3.3. But I'm using vinyl-ftp v0.4.5 (e.g. the current one on npm).

I used this project because it was referenced from [gulp-ftp](https://www.npmjs.com/package/gulp-ftp) and that was deprecated. However I got my files uploaded using gulp-ftp with the same settings.

**Comment by bartvanderwal** [comment]
I'm running Node on Windows (10). The FTP server does NOT support FTP/TSL.

```
[connection] < '220 \r\n'
[parser] < '220 \r\n'
[parser] Response: code=220, buffer=''
[connection] > 'USER memyselfandI'
[connection] < '331 Password required\r\n'
[parser] < '331 Password required\r\n'
[parser] Response: code=331, buffer='Password required'
[connection] > 'PASS $up3r$3cr3t(ButFaked:)'
[connection] < '230-Welcome to HostingPartner.nl\r\n'
[connection] < '230 User logged in.\r\n'
[parser] < '230-Welcome to HostingPartner.nl\r\n230 User logged in.\r\n'
[parser] Response: code=230, buffer='Welcome to HostingPartner.nl\r\nUser logged in.'
[connection] > 'FEAT'
[connection] < '211-Extended features supported:\r\n'
[connection] < ' LANG EN*\r\n UTF8\r\n AUTH TLS;TLS-C;SSL;TLS-P;\r\n PBSZ\r\n PROT C;P;\r\n CCC\r\n HOST\r\n SIZE\r\n MDTM\r\n REST STREAM\r\n211 END\r\n'
[parser] < '211-Extended features supported:\r\n LANG EN*\r\n UTF8\r\n AUTH TLS;TLS-C;SSL;TLS-P;\r\n PBSZ\r\n PROT C;P;\r\n CCC\r\n HOST\r\n SIZE\r\n MDTM\r\n REST STREAM\r\n211 END\r\n'
[parser] Response: code=211, buffer='Extended features supported:\r\n LANG EN*\r\n UTF8\r\n AUTH TLS;TLS-C;SSL;TLS-P;\r\n PBSZ\r\n PROT C;P;\r\n CCC\r\n HOST\r\n SIZE\r\n MDTM\r\n REST STREAM\r\nEND'
[connection] > 'TYPE I'
[connection] < '200 Type set to I.\r\n'
[parser] < '200 Type set to I.\r\n'
[parser] Response: code=200, buffer='Type set to I.'
[16:31:09] READY
[16:31:09] MLSD  /mysite/wwwroot/wp-content/plugins/mbm-charts
[connection] > 'PASV'
[connection] < '227 Entering Passive Mode (185,41,127,15,200,244).\r\n'
[parser] < '227 Entering Passive Mode (185,41,127,15,200,244).\r\n'
[parser] Response: code=227, buffer='Entering Passive Mode (185,41,127,15,200,244).'
[connection] PASV socket connected
[connection] > 'MLSD /mysite/wwwroot/wp-content/plugins/mbm-charts'
[connection] < '500 Command not understood.\r\n'
[parser] < '500 Command not understood.\r\n'
[parser] Response: code=500, buffer='Command not understood.'
[16:31:09] LIST  /mysite/wwwroot/wp-content/plugins/mbm-charts
[connection] > 'PASV'
[connection] < '227 Entering Passive Mode (185,41,127,15,200,245).\r\n'
[parser] < '227 Entering Passive Mode (185,41,127,15,200,245).\r\n'
[parser] Response: code=227, buffer='Entering Passive Mode (185,41,127,15,200,245).'
[connection] PASV socket connected
[connection] > 'LIST /mysite/wwwroot/wp-content/plugins/mbm-charts'
[connection] < '125 Data connection already open; Transfer starting.\r\n226 Transfer complete.\r\n'
[parser] < '125 Data connection already open; Transfer starting.\r\n'
[parser] Response: code=125, buffer='Data connection already open; Transfer starting.'
[parser] < '226 Transfer complete.\r\n'
[parser] Response: code=226, buffer='Transfer complete.'
[16:31:09] DISC
```

**Comment by bartvanderwal** [comment]
I did notice that gulp-ftp has nothing `conn.delete`, which I need. And I guess they probable won't maintain given they're deferring to your project.

@morris, if you want I could create a FTP account for you on the server I used.

**Comment by morris** [comment]
Is their an error event emitted? I think this is just trying MLSD which fails because the server does not support it, and then falling back to LIST without actually emitting an error; it's just logged.

**Comment by bartvanderwal** [comment]
Well you could be right. There is no error event in the log.

I probably missed that since I WAS expecting an error message. Because I could not find any files were sent the server. When I look at my code now, I think probably the problem was that I was missing a `.pipe(conn.dest(` at the end of the chain of my deploy task. I had this line commented out after copy-pasting from your example, as I interpreted the last two lines as two options when :
- second to last line when you want to replace only with newer fles
- last line if you want to replace all.

Perhaps you could issue a warning when there is no `dest`. Though probably some people just want to list. But maybe that could be made an explicit command, and you could try to enforce there to be at least one action.

But I now understand the second to last line is actually a toggle, and the last line is obligatory if you want anything to happen. It's just that `newer(arg)` doesn't really feel like an option, but more like an action :). And/or perhaps the newer function could be renamed to `setOptionToOnlyUploadFilesIfTheyAreNewerForTheFollowingPaths`. Nahh, that's just not as terse :).

Anyway, I will test it tomorrow, when I'm back on the machine that has my FTP passwords. And will close this issue if everything worksout. But you're free to close it now also if you want :smile:.

```javascript
    return gulp.src(globs, { cwd: '.', buffer: false } )
        .pipe(print())
        .pipe(confirm({ question: 'Je gaat uploaden naar TEST. Druk ALLEEN \'j\' als je het zeker weet :).',
                        input: '_key:j'})
        )
        .pipe(conn.newer(settings.remotePath)) // only upload newer files.
        // .pipe(conn.dest(settings.remotePath));  **<--the problem** 
```
