### ISSUE TITLE
excluding files with !

### ISSUE THREAD

**Issue by jacobraccuia** [morris/vinyl-ftp#37]
Took me a long time to learn this.  I don't know if it's gulp related or your program related, but it would be really really helpful if this was added to the documentation for anyone else who is not as knowledgeable, like me!

thanks for plugin though, it rules

**Comment by birjolaxew** [comment]
This is part of the glob documentation:

> Glob-related options are documented at [minimatch](https://www.npmjs.com/package/minimatch).

From where you can read that

> If the pattern starts with a ! character, then it is negated. [...]

Globs are used by most gulp-related plugins, so I think it's fair to divert readers elsewhere for info on them.

**Comment by jacobraccuia** [comment]
fair enough!! I am very new to gulp so I had no idea :)

**Comment by morris** [comment]
thanks @birjolaxew :beer:
