### ISSUE TITLE
"MLSD not understood" error

### ISSUE THREAD

**Issue by pyrsmk** [morris/vinyl-ftp#4]
Hi!

I don't know what I do wrong but I can't upload any file, all my tests ended with `ERROR { [Error: MLSD not understood] code: 500 }`.

Here my task, hope it will help : 

```js
gulp.task('deploy', ['css', 'js', 'images'], function(){

	var json = require('./config/ftp.json'),
		conf = prod ? json.prod : json.dev,
		conn = ftp.create({
			host: conf.host,
			user: conf.user,
			password: conf.pass,
			//parallel: 10,
			log: gutil.log
		});

	return gulp.src('components/', { base: '.', buffer: false })
		.pipe(plumber())
                // My dest is /pinon_dev
		.pipe(conn.newer(conf.dest))
		.pipe(conn.dest(conf.dest));

});
```

Thanks for the great work, anyway ;)

**Comment by morris** [comment]
It seems your server does not support MLSD and responds with error code 500, which I didn't expect - I just released a new version v0.3.2 which falls back to LIST in that case. Hope it works for you :-)

**Comment by morris** [comment]
Oh well, did tested it, and had to fix some more things for LIST to work as a fallback. v0.3.3 should work.

**Comment by pyrsmk** [comment]
Erf... Wrong click.

Thanks for your reactivity! But it still resists you, only directories are created but no file is uploaded :D

**Comment by pyrsmk** [comment]
It seems it does not handle recursion.

**Comment by morris** [comment]
but now, there's no error, right?

**Comment by pyrsmk** [comment]
Yep, no error!

**Comment by morris** [comment]
hmm, it's hard to tell what's going on. your FTP server seems to be behaving very differently from my test servers. can you paste the complete log?

maybe you can create an FTP user for me so i can test. otherwise, try logging an ftp.list( path, cb ) result for me. this might help

**Comment by pyrsmk** [comment]
Unfortunately, it's not my personal FTP server. How should I log this stuff? (I'm not really used to nodejs)

**Comment by morris** [comment]
since you're already using gutil.log, just copy from the terminal. you could also pipe the output to a file or something. or a screenshot :D

**Comment by pyrsmk** [comment]
Ok ^^ Here's the screenshot (I cannot copy from that console :s) : 

http://i.imgur.com/7nkVbHE.jpg

**Comment by morris** [comment]
ok so just to rule out the obvious... you're using `newer`, so maybe the files are already up-to-date? what happens if you remove `newer`?

**Comment by pyrsmk** [comment]
In fact, they're no files on the ftp and removing newer do the same.

**Comment by morris** [comment]
ok, now try replacing `conn.dest( ... )` with `gulp.dest( 'test' )` and see if your files are copied into the local `test` directory. just to make sure the bug is inside vinyl-ftp :)

**Comment by pyrsmk** [comment]
Now, it does nothing (there's no ftp log).

**Comment by morris** [comment]
yes, because it should only copy files locally to the `test` directory. is that happening?

**Comment by pyrsmk** [comment]
Ah ok! Yes, the files have been copied

**Comment by morris** [comment]
could you try to do the following in your task:

`conn.mkdirp( 'pinon_dev/testdir', function( err ) { gutil.log( err ); } );`

**Comment by pyrsmk** [comment]
http://i.imgur.com/aHShREl.jpg

**Comment by morris** [comment]
great, the issue seems to be close by. now try:

`conn.mlsdOrList( 'pinon_dev', function( err, files ) { gutil.log( err, files ); } );`

**Comment by pyrsmk** [comment]
http://i.imgur.com/fcmuDSq.jpg

**Comment by morris** [comment]
are you sure? the testdir shouldnt be there, unless the mkdirp from above printed a "MKD"... anyways, it's very hard to debug that remotely :-( maybe you can find out what's going on if you console.log a few things inside the vinyl-ftp source. it shouldn't be hard, the source is rather clean I think. sorry I can't help you for now... but without proper FTP access, debugging this by guessing is insane. can you find out what FTP software your server is running?

**Comment by pyrsmk** [comment]
I'll try to debug this stuff tomorrow, or the next week. I asked about what FTP server is running to the sysop. I'll keep you in touch ;)

**Comment by morris** [comment]
that'd be awesome, thanks for helping me out :)

**Comment by pyrsmk** [comment]
Hum... I'm sorry but I don't understand how the whole thing is working (how Gulp passes the `src` parameter, how directory recursion is implement). Can you clarify me this?

Otherwise, I can give you my FTP ids then you can debug in live ;)

**Comment by pyrsmk** [comment]
The FTP server is : proftpd 1.3.1-17lenny4

**Comment by morris** [comment]
great, just send ftp credentials to mb@morrisbrodersen.de and I'll see what I can do

**Comment by morris** [comment]
think i found the issue and patched it into v0.3.4 - let me know if this works :)

**Comment by pyrsmk** [comment]
Great! Now it works! But I'm wondering if I had set well the directories. I explain : 

- with `components` (or `components`) as directory, it just uploads the `components` directory but without all the sub-directories/files
- with `components/**/*`, it uploads everything I need

Is this intended? Maybe it's minimatch my nemesis?

Otherwise, I'll test further by setting several directories for my project. I'll let you know if all works as expected ;)

**Comment by pyrsmk** [comment]
All is working as expected! And it's really fast, impressive!

**Comment by morris** [comment]
awesome - actually, `components/**` should be enough to match everything in that directory. thanks for reporting!

**Comment by pyrsmk** [comment]
And thanks for fixing this issue quickly! That was critical for my project.
