### ISSUE TITLE
Does not upload some files

### ISSUE THREAD

**Issue by pyrsmk** [morris/vinyl-ftp#40]
I'm running into a weird issue. With all of my projects I never had this problem. I'm trying to upload a simple list of files : 

```
'application/**',
'cache/*',
'css/**',
'js/**',
'vendor/**',
'.htaccess',
'index.php',
```

But it keeps only uploading `vendor/**`. If I remove it, it doesn't upload anything. Adding `./` at the beginning of the path doesn't change anything either.

Have you got some thoughts on how to debug this?

**Comment by morris** [comment]
Try running with debug: console.log.bind( console )

**Comment by pyrsmk** [comment]
Sorry, I was really busy. There's no problem with your library, I fixed the bug ;)
