### ISSUE TITLE
Upload is ignoring subdirectories

### ISSUE THREAD

**Issue by kmh3785** [morris/vinyl-ftp#41]
gulp.task( 'deploy', function () {
    var conn = ftp.create( {
        host:     ftp_host,
        user:     ftp_login,
        password: ftp_pass,
        parallel: 10,
        log:      gutil.log
    });

    var globs = [
        'dist/wp-content/**/*'
    ];

    return gulp.src( globs, { base: 'dist', buffer: false } )
        .pipe( conn.dest( staging_url ) );

---

Everything seems to work fine on upload, but anything *under* a subdirectory is ignored.

For example, in a structure such as /foo/bar/, all files under /foo/ are uploaded, and /bar/ is created, but nothing in /bar/ is uploaded.

Any idea what's going on here?

**Comment by morris** [comment]
Try removing the /*

**Comment by kmh3785** [comment]
@morris Thanks for the reply, but that doesn't work. Without the /* the subdirectories aren't even created.

**Comment by morris** [comment]
Try running with debug: console.log.bind( console ) and paste the output
