### ISSUE TITLE
Check whether directory exists before calling mkdir

### ISSUE THREAD

**Issue by jordanwallwork** [morris/vinyl-ftp#43]
Is it possible to check whether a directory exists before calling mkdir? I'm writing a gulp upload script which fails after the first run as it attempts to recreate an already existing directory. I can't delete the remote directory as the ftp user does not have permission to delete remote files, only to create new files/directories.

Code's pretty standard but adding in case it's helpful

	gulp.task('upload-only', function() {
			var conn = getFtpConnection();
			return gulp.src(['code_drop/RetailGuardian.zip'], { base: '.', buffer: false } )
					.pipe( conn.dest('/RetailGuardian') );
	});

**Comment by morris** [comment]
It probably does but fails to detect that it exists. Need an environment to reproduce, otherwise I can't help

**Comment by ninjaonsafari** [comment]
I am facing the same issue. I already created a [stackoverflow question](
http://stackoverflow.com/questions/36766698/vinyl-ftp-cannot-create-a-file-when-that-file-already-exists).

Server: Windows 12 R2 Standard 64bit

**Comment by ninjaonsafari** [comment]
So the problem is that the search of the folder is case-sensitive. But when it creates the folder it is not case sensitive.

**Comment by morris** [comment]
ah yes, that makes sense since the windows filesystem is insensitive. so did you fix it by ensuring the case is correct everywhere?

i don't think a fix is possible from within vinyl-ftp, not without configuration at least.

**Comment by ninjaonsafari** [comment]
jap exactly i fixed it by correcting my config.

**Comment by morris** [comment]
cool :-)
