### ISSUE TITLE
'data' event of stream still fires after 'finish' event fired

### ISSUE THREAD

**Issue by meowlab** [morris/vinyl-ftp#44]
The stream returned by `conn.****` fires `finish` event **too** early, the `data` event still fires after `finish` fired. It's wired, can we fix it?

**Comment by morris** [comment]
Quick guess,  use "end" instead of "finish"

**Comment by meowlab** [comment]
Yes!!! It works!!!
My bad, I just noticed it's a readable stream
Thanks~
