### ISSUE TITLE
There is no option to exclude folder from local path.

### ISSUE THREAD

**Issue by andrewboot** [morris/vinyl-ftp#47]
Hi! I'd like to explaine, what I mean in title.
Let's say, that I have this ierarchy:
```
/
  app
  dist
  gulpfile.js
```
So I want to all files **from** `'dist'` (for 'distribution', with optimized files) folder be copied to my server path. Let it be `'www/domainname'`
When I tried to add `['./dist/**/*']` as my _globs_ variable, it copies `'dist'` folder **itself**.

The only way to solve this problem for now is to rename `'dist'` folder to `'domainname'` and they'll match. But this approach is bad for me (and I believe, for others too), because of the debugging all places, where `'dist'` folder was mentioned. Thanks in advance!

**Comment by morris** [comment]
Please post this question to StackOverflow. Only create issues if you're sure that it's a bug or a missing feature in vinyl-ftp.

**Comment by andrewboot** [comment]
I found a way, thank you!

**Comment by nealoke** [comment]
@andrewboot I am facing the same question, could you share your answer please?

**Comment by nealoke** [comment]
For people having the same issue the following will solve it :)

The `base` in `gulp.src(globs, {base:''}` is where the magic happens. If the content you want to upload is in a folder called "export", you can do the following: `gulp.src(globs, {base:'./export/'}`

This will upload all the files to your server withouth putting them in the "export" folder.
