### ISSUE TITLE
Upload going to wrong folder

### ISSUE THREAD

**Issue by Kratos-SA** [morris/vinyl-ftp#48]
My FTP user is already linked to the correct folder, and I am uploading everything in my app folder. But my files are being uploaded into a a folder called app even though I tell it not to. 

```
 var globs = ['app/**'];
    return gulp.src(globs, {base: 'dist', buffer: false}).pipe(conn.dest('./'));
```

**Comment by morris** [comment]
Please post this question to StackOverflow. Only create issues if you're sure that it's a bug or a missing feature in vinyl-ftp.
