### ISSUE TITLE
Mode does not apply

### ISSUE THREAD

**Issue by pyrsmk** [morris/vinyl-ftp#5]
Hi again ^^

Then, the `mode` method does not apply my `0777` mode. I verified the directory and it's good.

**Comment by morris** [comment]
oh well :) will look into that tomorrow, sorry for the ongoing problems!

**Comment by morris** [comment]
a quick test on your server worked well, may i see your gulpfile?

**Comment by pyrsmk** [comment]
```js
ftpClient.mode( conf.dest + '/cache/*', '0777' );
```

Where `ftpClient` is the connection and `conf.dest` equals to `/pinon_dev`. I have a `twig` directory in `cache/` (and later several more) that should be writable.

**Comment by pyrsmk** [comment]
But I probably don't use the method as expected :p

**Comment by morris** [comment]
It's intended to be used as a pass through stream. In your case, something like this should work:

```javascript
ftpClient.glob( conf.dest + '/cache/*' ).pipe( ftpClient.mode( conf.dest + '/cache', '0777' ) );
```

It globs all files in the cache directory, pipes the files to the mode stream, which in turn sends the CHMOD to the server.

The API was designed that way so you can upload and set mode in one chain of streams: `gulp.src( ... ).pipe( ftpClient.dest( ... ) ).pipe( ftpClient.mode( ... ) )`. It is kinda counter-intuitive in your case, though. Maybe a separate, complete glob+chmod method would be nicer...

**Comment by pyrsmk** [comment]
Then, what is the utility of having a `remoteFolder` option for `mode`?

**Comment by morris** [comment]
@pyrsmk See #6 - and thanks for pointing that out!
