### ISSUE TITLE
Vinyl-ftp rmdir -  Error: Remove directory operation failed.

### ISSUE THREAD

**Issue by Grigory90** [morris/vinyl-ftp#56]
The error occurs if the remote directory does not exist.

**Gulpfile.js**
```javascript
var gulp = require('gulp');
var ftp  = require('vinyl-ftp');

var cfg = require('./config.json');

gulp.task('default', ['cleanremote']);

gulp.task('cleanremote', function(cb) {
    var conn = ftp.create(cfg.ftp);
    return conn.rmdir('./ftp_remote_folder', cb);
});
```

**Cmd**

![Error](https://d1ro8r1rbfn3jf.cloudfront.net/ms_46758/y1tsRW2cx3ENBYou8lwWiQYf2FsRhI/MINGW64__d_Work_Projects_vinyl-ftp-issue%2B2016-06-19%2B00.14.43.png?Expires=1466360110&Signature=aZBfTkHgLXzfX8iwuKbIIhh1QBGUhT9meU1avArlEwV9fAVr5vyQnqzHviOyiDNv5q8k9jKHy5Y3GjzoqINpK7LVUKoS241U65hvqhn4j~fdkU9APl2JElACLbYI~KkhMgiIs-n7vKkU5OwFKMy8gJjFzSsomCT~Abq2mh2AxnWVnREN6ggnSVWYop2Az9oVtjyCSt-LbChYT4Lg-PXq~b3wv7kTnhjYthilWphP-pMfoQ0gqJ-nUbzfsfz4XFF6EjJi8mQAsOg73jm-tzTwvWJrnVTH1~vufw4eLyveS9r6nIG0zM4NDKmqoi4IQqS3WsiyeHgstjkxiAM81wuzGA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Info**

- Windows 10 x64
- Vinyl-ftp 0.5.0

**P.S.** If the remote folder exists, then everything is fine ...

**EDIT:** Solution this problem:
``` javascript
gulp.task('cleanremote', function(cb) {
    var conn = ftp.create(cfg.ftp);
    return conn.rmdir('./ftp_remote_folder', function(err){
    	cb();
    });
});
```

**Comment by morris** [comment]
Unfortunately, it's hard to know why the operation fails - "Remove directory operation failed" is not necessarily saying the directory exists and could be anything. It's also something the FTP server defines so vinyl-ftp cannot do anything about it. In your case I'd do rmdir( ..., function ( err ) { cb() } ); since you're not really interested in the error.

**Comment by Grigory90** [comment]
@morris  So I solved the problem, as you wrote. But I thought it was a ftp-vinyl bug :)

**Comment by morris** [comment]
Also, fs.unlink and fs.rmdir fail if the target does not exist, so it's valid to throw in ftp.rmdir. Invalid for now...
