### ISSUE TITLE
Check whether directory/file exists

### ISSUE THREAD

**Issue by DruMasterMunch** [morris/vinyl-ftp#59]
Is there a way to check if a file or directory exists bedore uploading, instead of creating automatically the path to uploaded files ?

**Comment by morris** [comment]
You could do `conn.remote( path, function ( err, info ) {} )` and see if info is set. Why would you want to do that?

**Comment by DruMasterMunch** [comment]
Working fine, thanks ! 

I have a fixed structure on my remote, and i want to be sure that we don't upload files at a location that doesn't exists. Just a safety check.
