### ISSUE TITLE
Conn.newer doesn't upload updated files

### ISSUE THREAD

**Issue by MaelstromCdn** [morris/vinyl-ftp#64]
Hi there,
I'm using vinyl-ftp to upload a project and am trying to use conn.newer to only upload changed files. The issue is I can change my index.html file as much as I want and it never gets uploaded. Here's my gulp task:
```
var devConn = {
    host:     'waws-prod-yt1-001.ftp.azurewebsites.windows.net',
    port:     21,
    user:     '<mylogin>',
    password: '<mypw>',
    parallel: 20,
    log:      gutil.log,
    debug: function(info) { console.log(info) }
};

gulp.task('deployment-dev', function () {
    var conn = vinylFtp.create(devConn);

    var globs = [
        'index.html'
    ];

    return gulp.src( globs, { base: './', buffer: false } )
        .pipe( conn.newer( './site/wwwroot' ) ) // only upload newer files
        .pipe( conn.dest( './site/wwwroot' ) );
});
```

Any thoughts?

**Comment by morris** [comment]
I'd hope it's because your server time and local file time are in different time zones. You could try the timeOffset option, see README

**Comment by MaelstromCdn** [comment]
Gave it a try and it still doesn't seem to be working right. We're 2 hours behind the server here so I tried a timeOffset of -120 and 120 with no success (never uploads the file). I did try -500 just to see and then it uploaded the file.

**Comment by MaelstromCdn** [comment]
Hmm, I have to set it to -360 in order for it to work properly. I'm beginning to suspect this is an issue with how Microsoft Azure's ftp interface works. Perhaps they're ftp frontend isn't in the same timezone as the actually hosting datacenter? I'm not sure how the ftp date comparison works but wouldn't it make more sense to convert both dates to UTC and then do the compare? That way there'd be no need for timeOffset. Just a thought.

**Comment by morris** [comment]
Definitely, unsure right now why it wasn't possible when i implemented it, i'll have to check

**Comment by MaelstromCdn** [comment]
Yep, could be a limitation of the date formats you get for each item.

**Comment by MaelstromCdn** [comment]
Okay, turns out Microsoft has their servers all set to UTC, hence the 6 hour offset from where I am. Thanks for your help!
