### ISSUE TITLE
Upload a file in different folder

### ISSUE THREAD

**Issue by dariospadoni** [morris/vinyl-ftp#8]
Hello
I'm trying to upload files inside a different remote folder than the local one.
For instance, I have a local file /build/index.html and I would like to deploy it on the root of the FTP /index.html and not inside remote "build" folder. Is there a way to achieve that? I'm playing with different combination of options but with no success so far...
Thanks

**Comment by morris** [comment]
Hi! That should work with something like:

```
return gulp.src( 'build/index.html', { base: 'build', buffer: false } )
        .pipe( conn.dest( '/' ) );
```

or `src( 'build/**', ... )`. It really depends on your complete use case, though
