### ISSUE TITLE
FTP host, username and password in an external file?

### ISSUE THREAD

**Issue by ralphbolliger** [morris/vinyl-ftp#85]
Is there any possibility to store the FTP host, username and password in an external file (e.g. `.vinylrc`) in order to keep it out of git (public repositories) via `.gitignore`?

**Comment by maviola5** [comment]
Hi Ralph,

You could try using dotenv: https://github.com/motdotla/dotenv and put .env in your .gitignore to keep it safe.

**Comment by ralphbolliger** [comment]
Awesome! This should work for me. Thank you!
