### ISSUE TITLE
Gulp Notify Support

### ISSUE THREAD

**Issue by SavePointSam** [morris/vinyl-ftp#9]
Just curious if there is a way to attach error/success messages to [gulp-notify](https://github.com/mikaelbr/gulp-notify). If not, is that something you'd consider adding?

Thanks!

**Comment by morris** [comment]
Have you tried using it? It seems gulp-notify just provides some streams that listen to data/error events which vinyl-ftp already emits. Not sure if and what has to be done to support gulp-notify.

**Comment by nwittwer** [comment]
After some messing around I think getting basic gulp-notify support is as easy as requiring the package and then adding the following after piping conn.dest('route'):

````
.pipe(notify({
    onLast: true,
    message: 'Upload to server complete!'
  }));
```

Example usage:
```
var gutil = require( 'gulp-util' );
var ftp = require( 'vinyl-ftp' );
var notify = require("gulp-notify"); // Adds native alert notifications

// Create Gulp task
gulp.task('deploy', () => {

  var conn = ftp.create( {
    host:     'ftp.site.com',
    user:     'username',
    password: 'password',
    parallel: 3,
    log:      gutil.log
  } );

  var globs = [
    'dist/**'
  ];

  return gulp.src( globs, { buffer: false } )
  .pipe( conn.newer( '/public_html/' ) ) // only upload newer files
  .pipe( conn.dest( '/public_html/' ) )
  .pipe(notify({
    onLast: true, // the magic
    message: 'Upload to server complete!'
  }));

}); // end deployment
```

**Comment by selrond** [comment]
@nwittwer Thank you! Works
