### ISSUE TITLE
conn.newer doesn't appear to work with Node v8+

### ISSUE THREAD

**Issue by JacobDB** [morris/vinyl-ftp#90]
I have a Gulp task that uploads changed files, but since installing Node v8 (specifically tested with v8.1.2), it doesn't appear to be working correctly anymore; New files get added just fine, but old files never get replaced, unless I first delete them off the server, or remove the "newer" check.

I've just tested with an older version of Node (v6.10.3), and the task worked exactly as expected.

[JacobDB/new-site/gulp-tasks/upload.js](https://github.com/JacobDB/new-site/blob/master/gulp-tasks/upload.js)

**Comment by moequraishi** [comment]
Same issue, this needs to be fixed asap.

**Comment by JacobDB** [comment]
Thanks, I thought I was going crazy for a while lol

**Comment by JacobDB** [comment]
After some testing, it appears to be a change in the way the times are retrieved with `remote.ftp.date` at [/lib/filter.js:23](https://github.com/morris/vinyl-ftp/blob/master/lib/filter.js#L23). My server's time is being reported in GMT, while my local time is CST (GMT-5). Setting the `timeOffset` to `-300` fixes the issue, but I didn't have to do this previously, so I'm not sure what changed.

Adding `console.log(ftp.stat.mtime);` and `console.log(remote.ftp.date)` to the `newer` function, I get the following reported:

    file.stat.mtime: Mon Jun 26 2017 10:49:00 GMT-0500 (CDT)
    remote.ftp.date: Mon Jun 26 2017 15:49:09 GMT-0500 (CDT)

As you can see, it thinks the remote time is in CDT even though it's actually being retrieved in GMT.

**Comment by JacobDB** [comment]
@morris I just tried looking in to this again, no luck. It seems like the local time is reporting accurately, but the remote time isn't. Can't figure out why. Any tips on where to look?

**Comment by JacobDB** [comment]
Keep coming back to this with no success. No matter what I try, I can't get the server time to be reported correctly. I guess I'll just have to resort to manually specifying the offset for now.

**Comment by JacobDB** [comment]
Now that Node v8 has moved in to LTS, it'd be awesome if this could be fixed.

**Comment by nandaleite** [comment]
I have noticed this problem recently (Newest files not being uploaded). 
Thanks for pointing out the remote.ftp.date issue.

Looks like Nodejs is converting the date to UTC automatically.

I am using this code as a workaround:

```
          if (modify) {
            var year = modify.substr( 0, 4 );
            var month = modify.substr( 4, 2 );
            var date = modify.substr( 6, 2 );
            var hour = modify.substr( 8, 2 );
            var minute = modify.substr( 10, 2 );
            var second = modify.substr( 12, 2 );
            var date = new Date(year + '-' + month + '-' + date + 'T' + hour + ':' +minute + ':' + second);
            var timezone = date.getTimezoneOffset() / 60;
            obj.date = date.setHours(date.getHours() - timezone);

          }
```


At mlsd.js
https://github.com/morris/vinyl-ftp/blob/10ba868c23de142a9f126c0a2d579fa61d9c37ce/lib/mlsd.js#L91-L100

**Comment by jacobraccuia** [comment]
nandaleite's solution worked for me, thank you!  running npm v 5.6.0, node v.8.9.4

**Comment by selrond** [comment]
Any news on this?

**Comment by jpacareu** [comment]
Well I don't know if this is a proper solution but I had to install Node Version Manager (for windows go [here](https://github.com/coreybutler/nvm-windows/releases) and install the **latest stable version** I mean the one with the green label next to it). Once this is done open the CMD and run 
`nvm install 7.10.1`
Wait for the installation to finish and type:
`nvm use 7.10.1`
and finally run your **gulp** command in your project. Hope it helps .... Cheers :)

**Comment by selrond** [comment]
@jpacareu the title of this issue explicitly mentiones `vinyl-ftp` not working with "Node v8+"; you've installed node `7.10.1`, so it's out of the scope of this issue.

**Comment by JacobDB** [comment]
So I just updated my tasks from CommonJS syntax to ESM syntax, and all of a sudden, uploads started doing this again. I did some debugging, the dates are actually *correct* now, but `vinyl-ftp` still doesn't upload. [This fork](https://github.com/gulpetl/vinyl-ftp) works, but only if I disable your patch. Very weird.

**Comment by JacobDB** [comment]
Commented earlier and deleted because I was wrong &ndash; I've now figured it out.

This started occurring again after I switched from CommonJS syntax to ESM syntax. No idea why, I'm honestly not familiar enough with the difference to understand, I'm just now learning about ESM. It appears that Node.js's `file.stat.mtime` simply doesn't contain timezone information for modified files, so `vinly-ftp` has no idea that the timezone is off. Instead, `vinly-ftp` offers an `timeOffset` parameter, which you can feed in the number of minutes you need to offset. This isn't ideal, as in places with DST, that time offset will change twice a year.

So, you can work around this by dynamically setting the `timeOffset` based on your local machine's timezone, like so:

```js
/**
 * Ensure timezone offset is set
 */
if (global.settings.ftp.timeOffset === null || global.settings.ftp.timeOffset === undefined) {
    const DATE = new Date();
    global.settings.ftp.timeOffset = DATE.getTimezoneOffset() * -1;
}
```

This assumes that your server is set to GMT time, your configuration object is set to `global.settings.ftp`, and that `timeOffset` hasn't been set, or is set to `null`. So far, this seems to be working perfectly, but I've only tested it in my own timezone (GMT-6), so I'm not sure how it'll work elsewhere in the world; in theory, it should be fine but the `* -1` has me concerned for some reason. In any case, this should be a good enough starting point to figure it out if your environment differs than mine.

Super frustrating issue, but I think this is a good enough solution for me, at least for now.
