### ISSUE TITLE
Dot files are being ignored

### ISSUE THREAD

**Issue by rahulnever2far** [morris/vinyl-ftp#92]
I have certain dot files (such as .csscomb, .scss-lint.yml, etc) in my project that I need on my server as well.

My globs are as follows
```
'./**',
'!./.git/**',
'!./node_modules/**',
```

All of my project files get transfered successfuly except the dot file. Is this a bug or by design?

**Comment by shroudedcode** [comment]
@rahulnever2far Have you set the `dot` option of the `options` object to `true`? It should look like this:
```javascript
gulp.src(globsArray, { dot: true })
```

**Comment by riklewis** [comment]
I came here to report the same issue, but using the "dot" option worked perfectly.

**Comment by rahulnever2far** [comment]
@shroudedcode thank you. It works fine when `dot` is set to true.
